export interface AcademicCasePreset {
  id: 'estable' | 'vigilancia' | 'critico';
  label: string;
  descripcion: string;
  clasificacionEsperada: 'ESTABLE' | 'VIGILANCIA' | 'CRITICO';
  data: Record<string, unknown>;
}

export const ACADEMIC_CASES: AcademicCasePreset[] = [
  {
    id: 'estable',
    label: 'Caso académico ESTABLE',
    descripcion: 'Paciente con parámetros clínicos en rango y sin datos de hipoperfusión.',
    clasificacionEsperada: 'ESTABLE',
    data: {
      inicialesPaciente: 'A.R.M.',
      edad: 45,
      sexo: 'FEMENINO',
      servicio: 'Medicina Interna',
      cama: 'MI-12',
      diagnosticoMedico: 'Neumonía en resolución clínica',
      motivoAtencion: 'Vigilancia general de enfermería y control de signos vitales.',
      frecuenciaCardiaca: 84,
      frecuenciaRespir: 18,
      tensionArterialSis: 118,
      tensionArterialDias: 74,
      presionArterialMedia: 89,
      temperatura: 36.8,
      saturacionO2: 96,
      glucosaCapilar: 112,
      escalaDolor: 2,
      glasgow: 15,
      diuresisHora: 0.8,
      ventilacionMecanica: false,
    },
  },
  {
    id: 'vigilancia',
    label: 'Caso académico VIGILANCIA',
    descripcion: 'Alteración respiratoria moderada con probable proceso infeccioso.',
    clasificacionEsperada: 'VIGILANCIA',
    data: {
      inicialesPaciente: 'M.C.P.',
      edad: 62,
      sexo: 'MASCULINO',
      servicio: 'Hospitalización',
      cama: 'H-07',
      diagnosticoMedico: 'Neumonía adquirida en la comunidad',
      motivoAtencion: 'Disnea progresiva, fiebre y vigilancia respiratoria estrecha.',
      frecuenciaCardiaca: 104,
      frecuenciaRespir: 28,
      tensionArterialSis: 110,
      tensionArterialDias: 68,
      presionArterialMedia: 82,
      temperatura: 38.4,
      saturacionO2: 92,
      glucosaCapilar: 154,
      escalaDolor: 4,
      glasgow: 14,
      diuresisHora: 0.6,
      gaso_pH: 7.34,
      gaso_PaCO2: 33,
      gaso_PaO2: 72,
      gaso_SaO2: 93,
      gaso_Lactato: 2.1,
      ventilacionMecanica: false,
      tipoO2: 'Mascarilla simple',
      fio2: 40,
    },
  },
  {
    id: 'critico',
    label: 'Caso académico CRÍTICO',
    descripcion: 'Compromiso respiratorio y hemodinámico con riesgo de shock.',
    clasificacionEsperada: 'CRITICO',
    data: {
      inicialesPaciente: 'J.L.S.',
      edad: 58,
      sexo: 'MASCULINO',
      servicio: 'UCI',
      cama: 'UCI-03',
      diagnosticoMedico: 'Sepsis pulmonar con insuficiencia respiratoria aguda',
      motivoAtencion: 'Inestabilidad hemodinámica y deterioro respiratorio severo.',
      frecuenciaCardiaca: 132,
      frecuenciaRespir: 34,
      tensionArterialSis: 82,
      tensionArterialDias: 48,
      presionArterialMedia: 59,
      temperatura: 39.1,
      saturacionO2: 84,
      glucosaCapilar: 248,
      escalaDolor: 7,
      glasgow: 10,
      diuresisHora: 0.25,
      gaso_pH: 7.19,
      gaso_PaCO2: 50,
      gaso_PaO2: 58,
      gaso_HCO3: 18,
      gaso_SaO2: 86,
      gaso_Lactato: 4.6,
      ventilacionMecanica: true,
      tipoO2: 'Ventilación mecánica invasiva (VMI)',
      modoVentilatorio: 'VCV (Volumen Controlado)',
      fio2: 0.8,
      peep: 10,
      frProgramada: 22,
      presionPico: 36,
      presionPlateau: 31,
      musculosAccesorios: true,
      sincroniaVentilador: false,
    },
  },
];
